line-length = 88
target-version = "py312"
extend-exclude = ["**/migrations", ".venv", "venv"]

[lint]
select = ["E", "F", "W", "N", "B", "ANN", "I", "RUF"]
ignore = ["ANN401"]

[lint.per-file-ignores]
"settings/env/*.py" = ["F403", "F405"]